name: "Podcast Generator"
author: "Test"
description: "Generate a feed for a podcast from a Yaml file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"

inputs:
  email:
    description: The commiter's email address
    required: true
    default: ${{github.actor}}@localhost
  name:
    description: The commiter's email address
    required: true
    default: ${{github.actor}}
